### ISSUE TITLE
Running tmhmm on test.fa fails

### ISSUE THREAD

**Issue by paulinaczheng** [dansondergaard/tmhmm.py#14]
Hi,

Thanks for creating this package. However, I am encountering an issue. Running `tmhmm -m TMHMM2.0.model -f test.fa`, I get the following error message:

/anaconda3/lib/python3.6/site-packages/tmhmm/__init__.py:21: RuntimeWarning: divide by zero encountered in log
  _, path = viterbi(sequence, *model)

Any insights/help would be greatly appreciated!

Thanks,
Paulina

**Comment by dansondergaard** [comment]
Hi Paulina,

That's just a warning. It doesn't really matter. The output files should exist and be correct.
