### ISSUE TITLE
predict() missing 1 required positional argument: 'model_or_filelike'

### ISSUE THREAD

**Issue by dgershlick** [dansondergaard/tmhmm.py#17]
This previously was working for me, but it is still possible i am doing something wrong. 

I am using: annotation,pos_memb=tmhmm.predict(fasta,'TMHMM.model'), as I iterate through a list of FASTA sequences. 

I am (now) getting the following error:
"TypeError: predict() missing 1 required positional argument: 'model_or_filelike'"

Any tips would be appreciated.

**Comment by bosborne** [comment]
@dgershlick this should work now. But just pass the protein sequence, not fasta.

`annotation,pos_memb=tmhmm.predict(seq)`
